language: node_js
sudo: required
node_js:
  - "10.15.3"
install:
  - yarn install
script:
  - yarn test
cache:
   directories:
     - node_modules
branches:
  only:
    - master
notifications:
  slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV